repos:

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: local
    hooks:
    -   id: docformatter
        name: Run docformatter
        entry: make docformatter
        language: system

-   repo: local
    hooks:
    -   id: black
        name: Run Black
        entry: make black
        language: system
